### PR TITLE
Remove node fetch

### PR DESCRIPTION
**Pull request by ovadiababayev**

### CODE REVIEW

**Comment by guysegal** [comment]
@noamokman wdyt?

**Comment by guysegal** [comment]
@ovadiababayev can you describe a bit what is the problem you faced?

**Comment by ovadiababayev** [comment]
I can't use it on client side app, since we have the build-in browser fetch and it doesn't compile (classes are different)

**Comment by noamokman** [comment]
@ovadiababayev we actually only use it for types and tests, it shouldn't be a problem for you.
Without the types the package loses a lot of type data.

I use it in a frontend app and it worked, maybe there is an issue with the wiring or build process

**Comment by ovadiababayev** [comment]
@noamokman It works with version 2.2.1 but updating to version 4.0.2 breaks it.

**Review by noamokman — APPROVED** [review]

**Pull request merged**
